name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: python --version
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install FLASK
        pip install pylint
    - name: Analiza kodu
      run: |
        pylint $(git ls-files '*.py')
